logging:
    level:
        com.itranlin.twin: debug
    file:
        name: ./logs/common-server.log
server:
    port: 8098
spring:
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    jackson:
        default-property-inclusion: non_null
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://127.0.0.1:3306/twin?useUnicode=yes&characterEncoding=UTF8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&allowMultiQueries=true


